### ISSUE TITLE
The build script(s) should be added as npm tasks.

### ISSUE THREAD

**Issue by w0298i** [mochi/mochikit#19]
I noticed this, and I have no idea on how to open a pr.
If you add npm scripts, you can then run the build scripts
from the base directory without `cd`ing to the `scripts` folder.
This makes it easier, by letting you type `npm run build`.

**Comment by etrepum** [comment]
GitHub has instructions for how to create a PR: https://help.github.com/articles/creating-a-pull-request/

MochiKit is an old library that predates npm and node by quite a bit and hasn’t been modernized. PRs to improve this would certainly be appreciated.

**Comment by w0298i** [comment]
I would be happy to improve MochiKit, as it is a very good library. Maybe a new v2 version with es6 modules?

**Comment by etrepum** [comment]
Sounds great, I have been thinking how nice it would fit in with modern JS (async/await, Promise, Iterator, etc.)

**Comment by w0298i** [comment]
I totally agree. It would be a shame to let MochiKit go to waste. The pull request is here:
https://github.com/w0298i/mochikit
if you want to merge it with master (im still learning)

**Comment by w0298i** [comment]
I was also thinking you could have es6 imports and then the MochiKit modules could be used separately, instead of being 'packed'.
